language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0

env:
  - LARAVEL_VERSION="4.2.*" EXCLUDED_GROUP="laravel5"
  - LARAVEL_VERSION="5.0.*" EXCLUDED_GROUP="laravel4"
  - LARAVEL_VERSION="5.1.*" EXCLUDED_GROUP="laravel4"
  - LARAVEL_VERSION="5.2.*" EXCLUDED_GROUP="laravel4"

matrix:
  exclude:
    - php: 5.4
      env: LARAVEL_VERSION="5.1.*" EXCLUDED_GROUP="laravel4"
    - php: 5.4
      env: LARAVEL_VERSION="5.2.*" EXCLUDED_GROUP="laravel4"

install:
  - travis_retry composer self-update
  - travis_retry composer require illuminate/support:${LARAVEL_VERSION} illuminate/database:${LARAVEL_VERSION} illuminate/console:${LARAVEL_VERSION} illuminate/config:${LARAVEL_VERSION}  --prefer-source --no-interaction --dev

script: phpunit --exclude-group=${EXCLUDED_GROUP}
