language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

env:
  - LARAVEL_VERSION="4.2.*"
  - LARAVEL_VERSION="5.0.*"
  - LARAVEL_VERSION="5.1.*"
  - LARAVEL_VERSION="5.2.*"
  - LARAVEL_VERSION="dev-master"

install:
  - composer require illuminate/support:${LARAVEL_VERSION}
  - composer require illuminate/database:${LARAVEL_VERSION}
  - composer require illuminate/console:${LARAVEL_VERSION}
  - composer require illuminate/config:${LARAVEL_VERSION}

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

script: phpunit
